- name: Mac machine setup
  hosts: localhost
  vars_files:
    - ./vars.yaml
  tasks:
    - import_tasks: tasks/git.yaml
    - import_tasks: tasks/cli-tools.yaml
    - import_tasks: tasks/zsh.yaml
    - import_tasks: tasks/dock.yaml
    # - import_tasks: ansible/tasks/fonts.yaml