- name: Tapping homebrew/cask-versions to get alternate versions
  community.general.homebrew_tap:
    name: homebrew/cask-versions
- name: Install GUI tools via brew casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: latest
    greedy: yes
    install_options: force
  with_items: "{{ gui_packages }}"
  ignore_errors: true # TODO - How to surface errors?